### ISSUE TITLE
Expand Cloud Build sample

### ISSUE THREAD

**Issue by damemi** [GoogleCloudPlatform/opentelemetry-collector-builder-sample#31]
The [Cloud Build sample](https://github.com/GoogleCloudPlatform/opentelemetry-collector-builder-sample/tree/main/build/cloudbuild) provides a very basic setup for building with cloud build. It should be expanded to show how users can take advantage of more features of cloud build/artifact registry builds (such as automated build triggers). Users should be encouraged to fork this repo and point a cloud build trigger at their own fork, with screenshots and/or `gcloud` tutorial steps. Finally, it should show how to activate one of these triggers (such as merging a commit to the fork) and the users see their own image built from github in artifact registry.

**Comment by psx95** [comment]
As part of resolving this issues, the following action items will be done - 
 - A new recipe *'cloudbuild-automation'* under `build/` will be added to this repo.
 - Following the newly added sample, the users can get a sense of how to use CloudBuild with GitHub to automate build tasks. 
    - The sample will be configured to build and push a Docker image containing a custom built Opentelemetry collector (*built using OpenTelemetry Collector Builder*) whenever there is a push to the main (or whatever branch is configured to be tracked). 
 - This recipe will contain terraform scripts to show what operations need to be done in Google Cloud in order to create the build trigger and artifact registry.
 - Detailed instructions on how to run the scripts, along with any troubleshooting docs, if necessary.
