### ISSUE TITLE
Which GCP-related components should we include?

### ISSUE THREAD

**Issue by punya** [GoogleCloudPlatform/opentelemetry-collector-builder-sample#5]
Currently we include the Google Cloud PubSub exporter and receiver. These aren't built or verified by our team. Should we

1.  include them as generally useful to GCP customers?
2.  include them but call out their support status?
3.  not include them?

**Comment by punya** [comment]
On a related note, why do we include the PubSub exporter/receiver but not the Cloud Spanner receiver?

**Comment by punya** [comment]
Should we include the [resource detection processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourcedetectionprocessor)?

**Comment by damemi** [comment]
I wasn't aware our team didn't own the PubSub exporter and receiver, but my goal was to include anything maintained by Google in this sample to tie in with GCP. If we aren't maintaining it, we probably don't want it here.

> On a related note, why do we include the PubSub exporter/receiver but not the Cloud Spanner receiver

~~I missed it because it didn't have "Google" in the name :)~~
Edit: wait, we do have it... assumed I must have missed it based on your comment https://github.com/GoogleCloudPlatform/opentelemetry-collector-builder-sample/blame/main/builder-config.yaml#L29-L30

> Should we include the [resource detection processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourcedetectionprocessor)?

Yes, I think so. Didn't even think about processors yet

**Comment by aabmass** [comment]
@damemi do you plan to work on this?

**Comment by damemi** [comment]
Closing this since we have examples for pubsub and spanner.

I also don't think we need to take a policy stance on "what" components to include. Since the goal of this repo is to show examples of various use cases, the components that will be included will naturally be included on a case-by-case basis.
